/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import CONTROLADOR.Controlador_Medicamentos;
import CONTROLADOR.Controlador_Usuarios;
import MODELO.Usuarios;
import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Dell
 */
public class Menu2 extends javax.swing.JFrame {
    Listar_Medicamento listM = new Listar_Medicamento();
    crear_user user = new crear_user();
    login log = new login();
    insert_Medic ins_medic = new insert_Medic();
    insert_paciente inspaci = new insert_paciente();
    Controlador_Medicamentos metod_medic = new Controlador_Medicamentos();
    Controlador_Usuarios cu = new Controlador_Usuarios();
   
    
    public Menu2() {
       setUndecorated(true) ;
        initComponents();
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
      AWTUtilities.setWindowShape(this, forma)  ;
        
        this.setLocationRelativeTo(null);  
        btn_buscarmedic.setVisible(false);
        btn_ingres_medic.setVisible(false);
        btn_REGISTROpaciente.setVisible(false);
    }
     
    
   
    
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ingres_medic = new javax.swing.JButton();
        btn_REGISTROpaciente = new javax.swing.JButton();
        btn_iniciarsesion = new javax.swing.JButton();
        btn_crearuser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_buscarmedic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ingres_medic.setBackground(new java.awt.Color(0, 255, 102));
        btn_ingres_medic.setText("INGRESAR MEDICAMENTOS");
        btn_ingres_medic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingres_medicActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingres_medic, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 170, 70));

        btn_REGISTROpaciente.setText("Ingresar nuevo paciente");
        btn_REGISTROpaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_REGISTROpacienteMouseClicked(evt);
            }
        });
        btn_REGISTROpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_REGISTROpacienteActionPerformed(evt);
            }
        });
        btn_REGISTROpaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_REGISTROpacienteKeyPressed(evt);
            }
        });
        getContentPane().add(btn_REGISTROpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 70));

        btn_iniciarsesion.setBackground(new java.awt.Color(0, 204, 102));
        btn_iniciarsesion.setText("INICIAR SESION");
        btn_iniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarsesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 140, 70));

        btn_crearuser.setText("CREAR USUARIO");
        btn_crearuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearuserMouseClicked(evt);
            }
        });
        btn_crearuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearuserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crearuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 140, 70));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEMA DE REGISTRO DE PACIENTES Y MEDICAMENTOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 460, 50));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell Administrador\\Pictures\\Fmenu.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 410));

        btn_buscarmedic.setText("BUSCAR MEDICAMENTO");
        btn_buscarmedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarmedicActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscarmedic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_REGISTROpacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_REGISTROpacienteKeyPressed
         
    }//GEN-LAST:event_btn_REGISTROpacienteKeyPressed

    private void btn_REGISTROpacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_REGISTROpacienteMouseClicked
      
    }//GEN-LAST:event_btn_REGISTROpacienteMouseClicked

    private void btn_REGISTROpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_REGISTROpacienteActionPerformed
          
    }//GEN-LAST:event_btn_REGISTROpacienteActionPerformed

    private void btn_ingres_medicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingres_medicActionPerformed
                 if(evt.getSource()==btn_ingres_medic){
                 ins_medic.setVisible(true);
                  this.setVisible(false);
                 } 

    }//GEN-LAST:event_btn_ingres_medicActionPerformed

    private void btn_crearuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearuserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearuserMouseClicked

    private void btn_crearuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearuserActionPerformed
        
        if(evt.getSource() == btn_crearuser){
        user.setVisible(true);
        this.setVisible(false);
        }
        
    }//GEN-LAST:event_btn_crearuserActionPerformed

    private void btn_iniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarsesionActionPerformed
        if(evt.getSource() == btn_iniciarsesion){
         
         log.setVisible(true);
         this.setVisible(false);
        }
    }//GEN-LAST:event_btn_iniciarsesionActionPerformed

    private void btn_buscarmedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarmedicActionPerformed
       if(evt.getSource() == btn_buscarmedic){
        listM.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_btn_buscarmedicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_REGISTROpaciente;
    public javax.swing.JButton btn_buscarmedic;
    public javax.swing.JButton btn_crearuser;
    public javax.swing.JButton btn_ingres_medic;
    public javax.swing.JButton btn_iniciarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
