/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import CONTROLADOR.Controlador_Medicamentos;
import CONTROLADOR.Controlador_Usuarios;
import com.sun.awt.AWTUtilities;
import java.awt.Color;

import java.awt.Shape;

import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Dell
 */
public class Menu extends javax.swing.JFrame {
    Listar_Paciente listP = new Listar_Paciente();
    Listar_Medicamento listM = new Listar_Medicamento();
    crear_user user = new crear_user();
    login log = new login();
    insert_Medic ins_medic = new insert_Medic();
    insert_paciente inspaci = new insert_paciente();
    Controlador_Medicamentos metod_medic = new Controlador_Medicamentos();
    Controlador_Usuarios cu = new Controlador_Usuarios();

    public Menu() {

        setUndecorated(true);

        initComponents();
        //jlb_barra.setBackground(Color.DARK_GRAY);
        jlb_barra.setOpaque(true);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 40, 40);
        AWTUtilities.setWindowShape(this, forma);
        this.setLocationRelativeTo(null);
        btn_crearuser.setVisible(false);
        btn_iniciarsesion.setVisible(false);

    }

    /**
     *
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ingres_medic = new javax.swing.JButton();
        btn_REGISTRO = new javax.swing.JButton();
        btn_iniciarsesion = new javax.swing.JButton();
        btn_crearuser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_buscarmedic = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jlb_barra = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_buscpaciente = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ingres_medic.setBackground(new java.awt.Color(204, 204, 255));
        btn_ingres_medic.setText("INGRESAR MEDICAMENTOS");
        btn_ingres_medic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ingres_medic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingres_medicActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingres_medic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 170, 70));

        btn_REGISTRO.setBackground(new java.awt.Color(204, 204, 255));
        btn_REGISTRO.setText("Ingresar nuevo paciente");
        btn_REGISTRO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_REGISTRO.setFocusCycleRoot(true);
        btn_REGISTRO.setFocusTraversalPolicyProvider(true);
        btn_REGISTRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_REGISTROMouseClicked(evt);
            }
        });
        btn_REGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_REGISTROActionPerformed(evt);
            }
        });
        btn_REGISTRO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_REGISTROKeyPressed(evt);
            }
        });
        getContentPane().add(btn_REGISTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 170, 70));

        btn_iniciarsesion.setBackground(new java.awt.Color(0, 204, 102));
        btn_iniciarsesion.setText("INICIAR SESION");
        btn_iniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarsesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 140, 70));

        btn_crearuser.setText("CREAR USUARIO");
        btn_crearuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearuserMouseClicked(evt);
            }
        });
        btn_crearuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearuserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crearuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 140, 70));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell Administrador\\Pictures\\nuevo_user.jpg")); // NOI18N
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 70, 70));

        btn_buscarmedic.setBackground(new java.awt.Color(204, 204, 255));
        btn_buscarmedic.setText("BUSCAR MEDICAMENTO");
        btn_buscarmedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarmedicActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscarmedic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 170, 70));

        jButton3.setText("-");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        jButton4.setText("X");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        jlb_barra.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jlb_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 30));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell Administrador\\Pictures\\iconpastilla-.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 70, 70));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell Administrador\\Pictures\\iconbuscar_medic.jpg")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 70, 70));

        btn_buscpaciente.setBackground(new java.awt.Color(204, 204, 255));
        btn_buscpaciente.setText("BUSCAR PACIENTE");
        btn_buscpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscpacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 170, 70));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell Administrador\\Pictures\\inoc_buscpacient.jpg")); // NOI18N
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 70, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell Administrador\\Pictures\\Fmenu.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 590, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_REGISTROKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_REGISTROKeyPressed

    }//GEN-LAST:event_btn_REGISTROKeyPressed

    private void btn_REGISTROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_REGISTROMouseClicked

    }//GEN-LAST:event_btn_REGISTROMouseClicked

    private void btn_REGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_REGISTROActionPerformed
        
        if (evt.getSource() == btn_REGISTRO) {
            inspaci.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_REGISTROActionPerformed

    private void btn_ingres_medicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingres_medicActionPerformed
        if (evt.getSource() == btn_ingres_medic) {
            ins_medic.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_btn_ingres_medicActionPerformed

    private void btn_crearuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearuserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearuserMouseClicked

    private void btn_crearuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearuserActionPerformed

        if (evt.getSource() == btn_crearuser) {
            user.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_btn_crearuserActionPerformed

    private void btn_iniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarsesionActionPerformed
        if (evt.getSource() == btn_iniciarsesion) {

            log.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_iniciarsesionActionPerformed

    private void btn_buscarmedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarmedicActionPerformed
        if (evt.getSource() == btn_buscarmedic) {
            listM.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_buscarmedicActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_buscpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscpacienteActionPerformed
        
        
        if (evt.getSource() == btn_buscpaciente) {
            listP.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_buscpacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_REGISTRO;
    private javax.swing.JButton btn_buscarmedic;
    public javax.swing.JButton btn_buscpaciente;
    public javax.swing.JButton btn_crearuser;
    public javax.swing.JButton btn_ingres_medic;
    public javax.swing.JButton btn_iniciarsesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlb_barra;
    // End of variables declaration//GEN-END:variables
}
